### ISSUE TITLE
Saving and loading training checkpoints 

### ISSUE THREAD

**Issue by Anchick** [IBM/aihwkit#385] opened 2022-06-03 21:49 UTC
## Description

I have a problem loading a training checkpoint. it gives me the following error:

```
File "/home/username/.conda/envs/aihwkit_cuda/lib/python3.8/site-packages/aihwkit-0.4.0-py3.8-linux-x86_64.egg/aihwkit/simulator/tiles/base.py", line 747, in forward_indexed
    return self.tile.forward_indexed(x_input, d_tensor, is_test)
RuntimeError: Error in rpu.h:418  Matrix indices not set yet!
```

I can save checkpoint file and run training itself without any issues, until I want to load a checkpoint (model and optimizer state dictionaries)

## How to reproduce

Here is the fragment of my training loop:

````
    if load_checkpoint:
        checkpoint = torch.load(checkpoint_filename)
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        # optimizer.regroup_param_groups(model)

    for epoch in range(0, epochs):
        print("Epoch:", epoch)
        train_data = sparse_data_generator(x_train, y_train, batch_size, nb_steps, nb_inputs,
                                           shuffle=True, flatten=True)  ###train data generator
        test_data = sparse_data_generator(x_test, y_test, batch_size, nb_steps, nb_inputs,
                                         shuffle=False, flatten=True)  ###Test data generator
        print(f'{datetime.now().time().replace(microsecond=0)} --- '
              f'Epoch: {epoch}\t' "training started")
        model, optimizer, train_loss = train_step(train_data, model, criterion, optimizer,
                                                  dataset_size=train_dataset_size,
                                                  input_shape=[batch_size, nb_steps, *sample_shape])
        train_losses.append(train_loss)

        if save_checkpoint:
            torch.save({
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                # 'epoch': epoch,
                # 'loss': train_loss,
            }, checkpoint_filename)

        with torch.no_grad():
            print(f'{datetime.now().time().replace(microsecond=0)} --- '
                  f'Epoch: {epoch}\t' "testing started")
            model, validation_loss, error, accuracy = test_evaluation(test_data, model, criterion,
                                                                      dataset_size=test_dataset_size,
                                                                      input_shape=[batch_size, nb_steps, *sample_shape])
            validation_losses.append(validation_loss)
            test_error.append(error)
````

## Expected behavior

If load_checkpoint is true, then load state dictionaries for model and optimizer from a saved checkpoint_file and commence training.

## Other information

* Pytorch version: 1.10
* Package version: 4.0
* OS: CentOS 7
* Python version: 3.8
* Conda version: 4.10.3

**Comment by maljoras** [comment] 2022-06-07 15:21
Hi Anchick:

Many thanks for submitting the issue! It seems that you are using an old version of the toolkit (0.4.0), as the current pip version is 0.6. Would it be possible to double check whether your issue persists with the new version? We have changed and addressed some of the loading/saving behavior and the issue might already be fixed in the new version. 

Many thanks!

**Comment by Anchick** [comment] 2022-06-07 15:25
Hello,

I have updated to 0.6 with CUDA support few days ago. The issue still persists.

Is there an example of how to properly use or save/load 'state_dictionary' for a model and an optimizer?

Many thanks!

**Comment by maljoras** [comment] 2022-06-07 16:05
I see. Could you post a minimal example that reproduces the error? E.g. the above code does not show what model you are using. 
Thanks!

**Comment by Anchick** [comment] 2022-06-07 18:12
I have tried with 04_Lenet5_training example, and saving/loading indeed works as intended.

I am trying to implement small Time-distributed network (Input data have additional 'time_step' dimension). 
As I see now, the error is due to my TimeDistributed class implementation.

```
conv_1_ideal = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3)
conv_2_ideal = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=2)
dense_3_ideal = nn.Linear(in_features=4608, out_features=10)

conv_1 = convert_to_analog(conv_1_ideal, RPU_CONFIG)
conv_2 = convert_to_analog(conv_2_ideal, RPU_CONFIG)
dense_3 = convert_to_analog(dense_3_ideal, RPU_CONFIG)

model = AnalogSequential(
    TimeDistributed(conv_1),
    nn.ReLU(),
    TimeDistributed(conv_2),
    nn.ReLU(),
    TimeDistributed(nn.Flatten()),
    TimeDistributed(dense_3),
)
model.cuda()

```
timeDistributed class merges batch and time_step dimensions, passes through a layer and restores batch and time_step dimensions to the layer output.
```
class TimeDistributed(nn.Module):
    def __init__(self, module, batch_first=True):
        super(TimeDistributed, self).__init__()
        self.module = module
        self.batch_first = batch_first

    def forward(self, x):
        if len(x.size()) <= 2:
            return self.module(x)
        rem_dims, first_2_dims = x.size()[2:], x.size()[:2]
        x_reshaped = x.contiguous().view(-1, *rem_dims)  # (samples * timesteps, [rest of input sizes input_size])
        y = self.module(x_reshaped)
        rem_dims_y, first_2_dims_y = y.size()[1:], y.size()[:1]
        if self.batch_first:
            y = y.contiguous().view(*first_2_dims, *rem_dims_y)  # (samples, timesteps, output_size)
        else:
            y = y.contiguous().view(*first_2_dims[::-1], *rem_dims_y)  # (timesteps, samples, output_size)
        return y
```

**Comment by maljoras** [comment] 2022-06-07 21:29
I still cannot quite reproduce it. Could be that I use pytorch 1.9 while you are using 1.10. I wonder whether you see a key in the `model.state_dict()` which looks like '0.module.fold_indices' ?

**Comment by Anchick** [comment] 2022-06-07 22:37
No I only see the following:
```
'0.module.bias'
'0.module.analog_ctx_0'
'0.module.analog_tile_state_0'
'2.module.bias'
'2.module.analog_ctx_0'
'2.module.analog_tile_state_0'
'5.module.bias'
'5.module.analog_ctx_0'
'5.module.analog_tile_state_0'
```
I will try again with pytorch 1.9

**Comment by maljoras** [comment] 2022-06-08 16:56
I see. Can you still post an complete example script where the error occurs ? That would be helpful.

**Comment by Anchick** [comment] 2022-06-09 18:49
Hello, I have reinstalled aihwkit 6.0 with pytorch 1.9, but the problem persists.

Here is the example code I have used to reproduce error:

```
import os
from datetime import datetime
import numpy as np
import torch
from torch import nn, cuda, device
from torchsummary import summary
from torchvision import datasets, transforms
from aihwkit.nn import AnalogLinear, AnalogSequential, AnalogConv2d
from aihwkit.optim import AnalogSGD
from aihwkit.nn.conversion import convert_to_analog
from aihwkit.simulator.configs import SingleRPUConfig, FloatingPointRPUConfig
# from aihwkit.utils.analog_info import analog_summary

class TimeDistributed(nn.Module):
    def __init__(self, module, batch_first=True):
        super(TimeDistributed, self).__init__()
        self.module = module
        self.batch_first = batch_first

    def forward(self, x):
        if len(x.size()) <= 2:
            return self.module(x)
        rem_dims, first_2_dims = x.size()[2:], x.size()[:2]
        x_reshaped = x.contiguous().view(-1, *rem_dims)  # (samples * timesteps, [rest of input sizes input_size])
        y = self.module(x_reshaped)
        rem_dims_y, first_2_dims_y = y.size()[1:], y.size()[:1]
        if self.batch_first:
            y = y.contiguous().view(*first_2_dims, *rem_dims_y)  # (samples, timesteps, output_size)
        else:
            y = y.contiguous().view(*first_2_dims[::-1], *rem_dims_y)  # (timesteps, samples, output_size)
        return y

def load_images(dataset="mnist", batch_size=64):
    # Here we load the Dataset
    transform = transforms.Compose([transforms.ToTensor()])
    if dataset== "mnist":
        root = os.path.expanduser("~/data/datasets/torch/mnist")
        train_dataset = datasets.MNIST(root, train=True, transform=transform, target_transform=None,
                                                          download=True)
        test_dataset = datasets.MNIST(root, train=False, transform=transform, target_transform=None,
                                                         download=True)
    elif dataset== "fashion_mnist":
        root = os.path.expanduser("~/data/datasets/torch/fashion-mnist")
        train_dataset = datasets.FashionMNIST(root, train=True, transform=transform, target_transform=None,
                                                   download=True)
        test_dataset = datasets.FashionMNIST(root, train=False, transform=transform, target_transform=None,
                                                  download=True)
    elif dataset== "cifar10":
        root = os.path.expanduser("~/data/datasets/torch/cifar10")
        train_dataset = datasets.CIFAR10(root, train=True, transform=transform, target_transform=None,
                                                   download=True)
        test_dataset = datasets.CIFAR10(root, train=False, transform=transform, target_transform=None,
                                                  download=True)
    elif dataset== "cifar100":
        root = os.path.expanduser("~/data/datasets/torch/cifar100")
        train_dataset = datasets.CIFAR100(root, train=True, transform=transform, target_transform=None,
                                                   download=True)
        test_dataset = datasets.CIFAR100(root, train=False, transform=transform, target_transform=None,
                                                  download=True)

    train_data = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    validation_data = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    return train_data, validation_data

def create_sgd_optimizer(model, learning_rate=0.01):
    optimizer = AnalogSGD(model.parameters(), lr=learning_rate)
    optimizer.regroup_param_groups(model)
    return optimizer

def train_step(train_data, model, criterion, optimizer, dataset_size= 50000, device='cuda'):
    total_loss = 0
    log_softmax_fn = nn.LogSoftmax(dim=1)
    model.train()
    for images, labels in train_data:
        images = images.to(device)
        labels = labels.to(device)

        ###Adds time-step dimension
        images = torch.unsqueeze(images.data, 1)
        images = images.expand(-1, 100, -1, -1, -1)

        optimizer.zero_grad()
        output = model(images)
        m = torch.sum(output, 1)
        log_p_y = log_softmax_fn(m)
        loss = criterion(log_p_y, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * images.size(0)
    epoch_loss = total_loss / dataset_size ### 60000 is a train dataset samples for MNIST
    return model, optimizer, epoch_loss

def test_evaluation(validation_data, model, criterion, dataset_size= 10000, device='cuda'):
    total_loss = 0
    predicted_ok = 0
    total_images = 0
    model.eval()
    log_softmax_fn = nn.LogSoftmax(dim=1)
    for images, labels in validation_data:
        images = images.to(device)
        labels = labels.to(device)

        ###Adds time-step dimension
        images = torch.unsqueeze(images.data, 1)
        images = images.expand(-1, 100, -1, -1, -1)

        pred = model(images)
        pred_timestep_summed = torch.sum(pred.data, 1)
        log_p_y = log_softmax_fn(pred_timestep_summed)
        loss = criterion(log_p_y, labels)
        total_loss += loss.item() * images.size(0)
        _, predicted = torch.max(pred_timestep_summed.data, 1)
        total_images += labels.size(0)
        predicted_ok += (predicted == labels).sum().item()
        accuracy_test = predicted_ok/total_images*100
        error_test = (1 - predicted_ok/total_images)*100

    # epoch_loss = total_loss / len(validation_data.dataset)
    epoch_loss = total_loss / dataset_size
    print("Error_test:", error_test)
    print("Accuracy_test:", accuracy_test)

    return model, epoch_loss, error_test, accuracy_test

def training_loop(model, criterion, optimizer, train_data, validation_data, epochs, print_every=1,
                  load_checkpoint=False, save_checkpoint=False):
    train_losses = []
    validation_losses = []
    test_error = []
    checkpoint_filename = "Test_checkpoint.pth.tar"
    if load_checkpoint:
        checkpoint = torch.load(checkpoint_filename)
        model.load_state_dict(checkpoint['model_state_dict'], strict=False, load_rpu_config=False)
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])

    for epoch in range(0, epochs):
        print("Epoch:", epoch)
        print(f'{datetime.now().time().replace(microsecond=0)} --- '
              f'Epoch: {epoch}\t' "training started")
        model, optimizer, train_loss = train_step(train_data, model, criterion, optimizer,
                                                  dataset_size=60000)
        train_losses.append(train_loss)

        if save_checkpoint:
            torch.save({
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                # 'epoch': epoch,
                # 'loss': train_loss,
            }, checkpoint_filename)

        with torch.no_grad():
            print(f'{datetime.now().time().replace(microsecond=0)} --- '
                  f'Epoch: {epoch}\t' "testing started")
            model, validation_loss, error, accuracy = test_evaluation(validation_data, model, criterion,
                                                                      dataset_size=10000)
            validation_losses.append(validation_loss)
            test_error.append(error)

        if epoch % print_every == (print_every - 1):
            print(f'{datetime.now().time().replace(microsecond=0)} --- '
                  f'Epoch: {epoch}\t'
                  f'Train loss: {train_loss:.4f}\t'
                  f'Valid loss: {validation_loss:.4f}\t'
                  f'Test error: {error:.2f}%\t'
                  f'Accuracy: {accuracy:.2f}%\t')

    np.savetxt(os.path.join(RESULTS, "Test_error.csv"), test_error, delimiter=",")
    np.savetxt(os.path.join(RESULTS, "Train_Losses.csv"), train_losses, delimiter=",")
    np.savetxt(os.path.join(RESULTS, "Valid_Losses.csv"), validation_losses, delimiter=",")

    return model, optimizer, (train_losses, validation_losses, test_error)

RPU_CONFIG = FloatingPointRPUConfig()

USE_CUDA = 0
device = device('cuda' if cuda.is_available() else 'cpu')
if cuda.is_available():
    print("CUDA is available!")
    USE_CUDA = 1

SEED = 123
RESULTS = os.path.join('data', 'DATASET', 'results_aihwkit')

nb_inputs = 1*28*28
nb_outputs = 10
batch_size = 128
learning_rate = 0.03
n_epochs = 10

nb_steps = 100

dtype = torch.float

os.makedirs(RESULTS, exist_ok=True)
torch.manual_seed(SEED)

train_set, val_set = load_images(batch_size= batch_size, dataset='mnist')

conv_1_ideal = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3)
conv_2_ideal = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=2)
dense_3_ideal = nn.Linear(in_features=4608, out_features=10)

conv_1 = convert_to_analog(conv_1_ideal, RPU_CONFIG)
conv_2 = convert_to_analog(conv_2_ideal, RPU_CONFIG)
dense_3 = convert_to_analog(dense_3_ideal, RPU_CONFIG)

model = AnalogSequential(
    TimeDistributed(conv_1),
    nn.ReLU(),
    TimeDistributed(conv_2),
    nn.ReLU(),
    TimeDistributed(nn.Flatten()),
    TimeDistributed(dense_3),
)
model.cuda()

print(model)

summary(model, (nb_steps, 1, 28, 28))

print(f'\n{datetime.now().time().replace(microsecond=0)} --- '
      f'Started time-distributed network trainig, MNIST')

optimizer = create_sgd_optimizer(model, learning_rate=learning_rate)
criterion = nn.CrossEntropyLoss()
model, optimizer, _ = training_loop(model, criterion, optimizer, train_set, val_set,
                                    epochs= n_epochs, load_checkpoint=True, save_checkpoint=True)
model_dict = model.state_dict()
print(model_dict)
print(f'{datetime.now().time().replace(microsecond=0)} --- '
      f'Completed time-distributed network trainig, MNIST')
```

**Comment by Anchick** [comment] 2022-06-10 21:38
Here is a minimized version that triggers an error:

```
import os
from datetime import datetime

import numpy as np


import torch
from torch import nn, cuda, device
from torchsummary import summary
from torchvision import datasets, transforms

from aihwkit.nn import AnalogLinear, AnalogSequential, AnalogConv2d
from aihwkit.optim import AnalogSGD
from aihwkit.nn.conversion import convert_to_analog
from aihwkit.simulator.configs import SingleRPUConfig, FloatingPointRPUConfig
# from aihwkit.utils.analog_info import analog_summary

class TimeDistributed(nn.Module):
    def __init__(self, module, batch_first=True):
        super(TimeDistributed, self).__init__()
        self.module = module
        self.batch_first = batch_first

    def forward(self, x):
        if len(x.size()) <= 2:
            return self.module(x)
        rem_dims, first_2_dims = x.size()[2:], x.size()[:2]
        x_reshaped = x.contiguous().view(-1, *rem_dims)  # (samples * timesteps, [rest of input sizes input_size])
        y = self.module(x_reshaped)
        rem_dims_y, first_2_dims_y = y.size()[1:], y.size()[:1]
        if self.batch_first:
            y = y.contiguous().view(*first_2_dims, *rem_dims_y)  # (samples, timesteps, output_size)
        else:
            y = y.contiguous().view(*first_2_dims[::-1], *rem_dims_y)  # (timesteps, samples, output_size)
        return y

def create_sgd_optimizer(model, learning_rate=0.01):
    optimizer = AnalogSGD(model.parameters(), lr=learning_rate)
    optimizer.regroup_param_groups(model)
    return optimizer

RPU_CONFIG = FloatingPointRPUConfig()

USE_CUDA = 0
device = device('cuda' if cuda.is_available() else 'cpu')
if cuda.is_available():
    print("CUDA is available!")
    USE_CUDA = 1

SEED = 123
RESULTS = os.path.join('data', 'DATASET', 'results_aihwkit')
batch_size = 32
learning_rate = 0.03
epochs = 10
n_time_steps = 100
channels = 1
height = 28
width = 28
number_of_batches = 10 ###Number of batches in each epoch
dtype = torch.float
checkpoint_filename = "Test_checkpoint.pth.tar"

os.makedirs(RESULTS, exist_ok=True)
torch.manual_seed(SEED)

conv_1_ideal = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3)
conv_2_ideal = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=2)
dense_3_ideal = nn.Linear(in_features=4608, out_features=10)

conv_1 = convert_to_analog(conv_1_ideal, RPU_CONFIG)
conv_2 = convert_to_analog(conv_2_ideal, RPU_CONFIG)
dense_3 = convert_to_analog(dense_3_ideal, RPU_CONFIG)

model = AnalogSequential(
    TimeDistributed(conv_1),
    nn.ReLU(),
    TimeDistributed(conv_2),
    nn.ReLU(),
    TimeDistributed(nn.Flatten()),
    TimeDistributed(dense_3),
)
model.cuda()
print(model)
summary(model, (n_time_steps, 1, 28, 28))

optimizer = create_sgd_optimizer(model, learning_rate=learning_rate)
criterion = nn.CrossEntropyLoss()
log_softmax_fn = nn.LogSoftmax(dim=1)

for epoch in range(0, epochs):  ###Training epoch
    print("Epoch:", epoch)
    print(f'{datetime.now().time().replace(microsecond=0)} --- '
          f'Epoch: {epoch}\t' "training started")
    model.train()
    for i in range(number_of_batches):  ###Training step
        images = torch.rand(batch_size, n_time_steps, channels, height, width, device=device)
        labels = torch.randint(low=0, high=9, size=(batch_size,), device=device)
        optimizer.zero_grad()
        output = model(images)
        m = torch.sum(output, 1)
        log_p_y = log_softmax_fn(m)
        loss = criterion(log_p_y, labels)
        loss.backward()
        optimizer.step()
print("Training stopped")
print("Saving_checkpoint!")
torch.save({'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict()}, checkpoint_filename)
print("Loading_checkpoint!")
checkpoint = torch.load(checkpoint_filename)
model.load_state_dict(checkpoint['model_state_dict'], strict=False)
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])

print("Training continued from a checkpoint")
for epoch in range(0, epochs):  ###Training epoch
    print("Epoch:", epoch)
    print(f'{datetime.now().time().replace(microsecond=0)} --- '
          f'Epoch: {epoch}\t' "training started")
    model.train()
    for i in range(number_of_batches):  ###Training step
        images = torch.rand(batch_size, n_time_steps, channels, height, width, device=device)
        labels = torch.randint(low=0, high=9, size=(batch_size,), device=device)
        optimizer.zero_grad()
        output = model(images)
        m = torch.sum(output, 1)
        log_p_y = log_softmax_fn(m)
        loss = criterion(log_p_y, labels)
        loss.backward()
        optimizer.step()
model_dict = model.state_dict()
print(model_dict)
print(f'{datetime.now().time().replace(microsecond=0)} --- '
      f'Completed time-distributed network training, MNIST')
```

**Comment by Anchick** [comment] 2022-06-23 18:21
Yes, I can confirm that using identical new model resolved the issue, but reusing old model still have the issue after the re-compiling.

**Closed** 2022-06-24 18:18 UTC
Labels: bug

**Comment by maljoras** [comment] 2022-06-24 18:47
@Anchick I did not yet merge the fix. Now it is merged and the issue should be resolved.

**Comment by Anchick** [comment] 2022-06-24 22:02
Confirmed. It is working properly now. 

Thank you for your help!
